---
name: 'Docstring Auditor'
author: 'Rob Luke'
description: 'Use AI to review your code documentation.'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/rob-luke/docstring-auditor:latest'
branding:
  icon: 'check-square'
  color: 'white'
