---
name: 'Docstring Auditor'
author: 'Rob Luke'
description: 'Use AI to review your code documentation.'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/rob-luke/docstring-auditor:latest'
branding:
  icon: 'check-square'
  color: 'white'

inputs:
  analysis-path:
    description: 'Path to the file or directory you wish to analyse'
    required: false
    default: '/repo'
  openai-api-key:
    description: 'Your OpenAI API key'
    required: true
    default: 'sk-XXXX'

runs:
  using: "composite"
  steps:
    - run: echo I will process ${{ inputs.analysis-path }}.
      shell: bash
