name: Docker Image Release

on:
  push:
    branches:
      - 'main'

jobs:
  version:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t docstring-auditor .

      - name: Rename base image tag for release
        run: docker tag docstring-auditor ghcr.io/rob-luke/docstring-auditor:main

      - name: List docker images
        run: docker images

      - name: Push image to github
        run: docker push ghcr.io/rob-luke/docstring-auditor:main
